### ISSUE TITLE
Container outbound connection count limiting

### ISSUE THREAD

**Issue by IvanHristov98** [cloudfoundry/silk-release#30]
## Issue

Currently `silk` does not limit the number of connections that could be opened by app containers. This could be grounds for the noisy neighbor problem. In fact we already had a couple of outages where some apps that had opened too many (short lived) connections to a single host lead to a port exhaustion on the NAT Gateway.

## Context

This occurs with:
- `silk-release v2.36.0`
- os `ubuntu v18.04` regardless of whether it is `bionic` or `xenial`

## Steps to Reproduce

To reproduce the issue with the NAT GW port exhaustion simply deploy an application the instances of which try to open more than 55k connections in total to a single host. Note that the app instances should be deployed in a single private subnet with a single NAT GW.

## Expected result

The total amount of connections and the rate at which they are opened is limited per app instance.

## Current result

The total amount of connections per app instance is currently not limited.

## Possible Fix

I managed to produce this [spike](https://github.com/IvanHristov98/silk-release/pull/1/files) in a fork of `silk-release`. The change exposes configuration in `silk-cni` to optionally apply connection count limits to each container.

Limiting is achieved by appending two rules to the `netout` chains. The first uses the `connlimit` module of `iptables` to apply hard limits while the second - the `hashlimit` module of `iptables` to apply rate limits. Additionally logging chains for packets denied due to the hard limits and rate limits are added for better collection of data.

To test the spike I used two apps. A client that opens long lived tcp connections (60s of lifespan) to a respective tcp server.

**Comment by IvanHristov98** [comment]
Hi 👋, I managed to produce the PR above that should solve the issue with apps opening multiple short-lived connections through rate limiting. More details could be found in the linked PR.

The docker and template tests run successfully. I'm having issues with the acceptance tests though.

**_Is it correct that the acceptance tests for this repo are implemented as part of the [cf-networking-release](https://github.com/cloudfoundry/cf-networking-release/blob/develop/scripts/test-acceptance) and I have to run them in order to verify my work?_** I couldn't find any contributing docs stating this but thought of it because in every release note it is said explicitly that `silk-release` is being tested by `cf-networking-release`.

I also had some issues with running the acceptance tests on a `bbl` managed `bosh-lite` with a verified release  because most of them timed out (only 5 successful from 21). 😅 **_Do you have any recommendations/recipe to how to configure bosh-lite with cf so that I could successfully run the acceptance tests?_**

Thanks in advance.

**Comment by ameowlia** [comment]
Hi @IvanHristov98 , 

Apologizes for the lack of response. If you ever feel like we aren't responding please ping us on slack. We are in charge of [a ridiculous amount of repos](https://github.com/cloudfoundry/community/pull/142/files#diff-681ae1d72cecfd9bf8ad55ccc11c122f0469ddb09e540dfa272f13209cdb29d6R89-R168) and sometimes things get dropped.

> Is it correct that the acceptance tests for this repo are implemented as part of the cf-networking-release and I have to run them in order to verify my work?  I couldn't find any contributing docs stating this but thought of it because in every release note it is said explicitly that silk-release is being tested by cf-networking-release.

That is correct. The acceptance tests for both cf-networking-release and silk-release are kept in the cf-networking-release repo. 

More context: The releases are separate because silk-release is swappable. For example, some of VMware's customers use an NSX-T CNI instead. However, for the open source, both silk and cf-networking release are required for basically all features: container create, ASGs, c2c networking, service discovery, etc. Since they are so inter connected we only have one test suite and one CI/CD pipeline. Every time we cut a new release of cf-networking-release we also cut a new release of silk-release with the same version number, and vice versa. We do this to make sure they are always in sync and so we don't have to make complicated compatibility matrices. 

It would be great if you could update the docs to make this clearer for devs after you.

> Do you have any recommendations/recipe to how to configure bosh-lite with cf so that I could successfully run the acceptance tests?

No, we do not use bosh lites, we only use full cf-d environments when testing. It does not surprise me that all of the networking tests do not work with bosh-lite.

**Comment by IvanHristov98** [comment]
Hi Amy and thanks for the response. I've been wondering about why the repositories are split for quite some time already.
Anyways I've implemented an optional acceptance test and updated the docs in cf-networking-release with this [PR](https://github.com/cloudfoundry/cf-networking-release/pull/89) in the mean time.

**Comment by geofffranks** [comment]
hey @IvanHristov98. I ran into more go mod related issues with the various PRs for this, so I ended up just merging + resolving them directly. However now, running into this issue in CI:

```
13:46:50
• Failure [11.017 seconds]
13:46:50
Outbound connection limit
13:46:50
/tmp/build/1f5f819e/cf-networking/src/code.cloudfoundry.org/test/acceptance/outbound_conn_limit_test.go:26
13:46:50
  when an app opens multiple connections to one host
13:46:50
  /tmp/build/1f5f819e/cf-networking/src/code.cloudfoundry.org/test/acceptance/outbound_conn_limit_test.go:45
13:46:50
    the connections get rate limited [It]
13:46:50
    /tmp/build/1f5f819e/cf-networking/src/code.cloudfoundry.org/test/acceptance/outbound_conn_limit_test.go:46
13:46:50

13:46:50
    Expected
13:46:50
        <int>: 1
13:46:50
    to match exit code:
13:46:50
        <int>: 0
13:46:50

13:46:50
    /tmp/build/1f5f819e/cf-networking/src/code.cloudfoundry.org/test/acceptance/init_test.go:113
```

If you have any ideas, I'd appreciate it, otherwise I'll keep digging into it tomorrow. I ran it a couple times, and failed the same way both times. (the opsfile to enable it is applied in the CI environment)

**Comment by IvanHristov98** [comment]
Ohhh, I see I've made a mistake by forgetting to remove the `FDescribe` and changing it to `Describe`. Ooopsie. I need to fix that.
I see that it fails when trying to push the proxy app in [here](https://github.com/cloudfoundry/cf-networking-release/blob/a8cb84be485f5405234a965ae8cb92958eab32d0/src/code.cloudfoundry.org/test/acceptance/init_test.go#L113). To debug this we need to obtain the logs from the proxy app.

**Comment by IvanHristov98** [comment]
I created the PR with the fix for the removal of the test focus. Anyways to fully debug this we would need to extract why the proxy app fails to get deployed.

**Comment by geofffranks** [comment]
I had to make a few tweaks to the test and spammer related to gomod and the ci environment, but it's passing now.

Should be out in the next release. Thanks for the patience  + PRs!
